# Generate the site with this PR code to check it
name: Generate the site for testing

on:
  # Runs on PRs targeting the default branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just testing
  # TODO add some light site tests/sanity checks here
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'
      - name: Clean install of NPM packages
        run: npm ci
      - name: Build the site
        run: npm run build
      - name: List built site files
        run: ls -al _site/
